allowBuilds:
  '@nestjs/core': false
  '@prisma/engines': true
  '@scarf/scarf': false
  '@swc/core': true
  better-sqlite3: true
  prisma: true
  unrs-resolver: true
overrides:
  '@hono/node-server': 1.19.13
